### ISSUE TITLE
No such module 'WebRTC.RTCAudioSession' Error on iOS

### ISSUE THREAD

**Issue by hungvu193** [sendbird/quickstart-calls-directcall-react-native#1]
just tried to clone and run on my end, it didn't work
<img width="768" alt="Screen Shot 2022-09-14 at 14 42 27" src="https://user-images.githubusercontent.com/16502320/190092343-a2a02a13-d1c2-4f7e-b509-e6b15549d831.png">
I'm using Mac Monterey, Xcode 13.4.1

**Comment by bang9** [comment]
Hi @hungvu193, can you try updating the cocoapods itself to version 1.11.3?

**Comment by hungvu193** [comment]
@bang9 thank you, it worked after I upgrade cocoapod to 1.11.3 version. I'll try to integrate this into my main project and let you know the result 👍
