### ISSUE TITLE
SendbirdCalls.setListener does not work well on Android.

### ISSUE THREAD

**Issue by k0502s** [sendbird/quickstart-calls-directcall-react-native#5]
App.js

```// Setup onRinging
SendbirdCalls.setListener({
  onRinging: async (call) => {
    const directCall = await SendbirdCalls.getDirectCall(call.callId);

    if (!SendbirdCalls.currentUser) {
      const credential = await AuthManager.getSavedCredential();

      if (credential) {
        // Authenticate before accept
        await SendbirdCalls.authenticate(credential);
      } else {
        // Invalid user call
        return directCall.end();
      }
    }

    const unsubscribe = directCall.addListener({
      onEnded({ callId, callLog }) {
        AppLogger.info('[onRinging/onEnded] add to call history manager');
        callLog && CallHistoryManager.add(callId, callLog);
        unsubscribe();
      },
    });

    // Show interaction UI (Accept/Decline)
    if (Platform.OS === 'android') {
      await startRingingWithNotification(call);
    }
    if (Platform.OS === 'ios') {
      await startRingingWithCallKit(call);
    }
  },
});```


SendbirdCalls.setListener does not work well on Android.

As soon as you send a signal, <SendbirdCalls.setListener({})> is onRing does not work, and when you turn off and on again the app, onRing only works.

**Comment by bang9** [comment]
@k0502s Could you check if the FCM was received successfully?

**Comment by bang9** [comment]
Did you check that in the `messaging().onMessage`?

**Comment by k0502s** [comment]
@bang9 

`/** Firebase RemoteMessage handler **/
export function setFirebaseMessageHandlers() {
  const firebaseListener = async (message: FirebaseMessagingTypes.RemoteMessage) => {
    SendbirdCalls.android_handleFirebaseMessageData(message.data);
  };
  messaging().setBackgroundMessageHandler(firebaseListener);
  messaging().onMessage(firebaseListener);
}`

I don't think this function will work when I make a call.

**Comment by bang9** [comment]
@k0502s Have you changed the project configuration to yours?
[here](https://github.com/sendbird/quickstart-calls-directcall-react-native/blob/main/android/app/google-services.json) and [here](https://github.com/sendbird/quickstart-calls-directcall-react-native/blob/main/android/app/build.gradle#L138)

**Comment by k0502s** [comment]
@bang9 

Thank you. Looking at the dashboard, I saw that you registered the firebase server key on chat
